### ISSUE TITLE
add version as meta tag to index.html and inject it in routes and controllers 

### ISSUE THREAD

**Issue by jelhan** [ember-cli/ember-cli-app-version#16]
I was using [ember-cli-build-info](https://github.com/elidupuis/ember-cli-build-info) before. @elidupuis now dropped support for `ember-cli-build-info` in favour of `ember-cli-app-version`.

`ember-cli-build-info` adds version information to builds as meta tag in index.html and injects it in routes and  controllers. Following documentation of `ember-cli-app-version` it only adds version information to ember inspector. Is there any functionality planed or already implemented but not documented like `ember-cli-build-info` had?

**Comment by elidupuis** [comment]
@jelhan, I've updated ember-cli-build-info, see https://github.com/elidupuis/ember-cli-build-info/releases/tag/v0.1.0.

I'm curious what the ember-cli-app-version maintainers think about the the `meta` tag injection being an option in this addon.

**Comment by MiguelMadero** [comment]
It's on the environment config, so you could simply set storeConfigInMeta and it will be there. Also, if you need to access this information from routes or controllers, you could import './config/environment'...

**Comment by MiguelMadero** [comment]
Just updating my own comment one year later. This is still an issue since ember-cli grabs the values of config.APP and adds them to your JS to pass them as defaults. This is a patch that is working for us: 

```
EmberApp.prototype._contentForAppBoot = function(content, config) {
    if (this.options.autoRun) {
      content.push('if (!runningTests) {');
      content.push('  (function () {');
      content.push('    var appConfig = require("' + config.modulePrefix + '/config/environment").default.APP || {};');
      content.push('    require("' +
        config.modulePrefix +
        '/app")["default"].create(appConfig);');
      content.push('  })();');
      content.push('}');
    }
  };
```

I'll open a separate PR/Issue against Ember CLI. The main problem I have with the current default is that it invalidates the cache for my JS on each revision. If we have CSS only changes, I don't want the JS to end up with a different fingerprint.

**Comment by stefanpenner** [comment]
> I'm curious what the ember-cli-app-version maintainers think about the the meta tag injection being an option in this addon.

What problem does that solve? That importing this helper directly, or config.App.version doesn't address?

**Comment by jelhan** [comment]
> What problem does that solve? That importing this helper directly, or config.App.version doesn't address?

For me it was only about backward compatibility. It could be easily done in an application initializer. So there isn't a good reason at all to include the feature in this addon.

Importing the config is even more easy than injecting a service. Injecting services by default is not a good idea at all. So also the other point raised by me in this issue isn't valid anymore.

I will close this issue for now. Feel free to reopen.
