### ISSUE TITLE
hideSha Option does not work for more complex Version numbers

### ISSUE THREAD

**Issue by omarkohl** [ember-cli/ember-cli-app-version#37]
For example the following are all valid [SemVer](http://semver.org/) Versions and they are not accepted by the helper when the hideSha Option is used. What is worse it breaks the whole app.

* 1.10.0 (Version number with more than one digit)
* 1.0.0-alpha.1 (Version number with a pre-release)

The second example doesn't actually raise an error but it is just stripped from the version (would return 1.0.0).

The reason being that the versionRegExp used doesn't match those cases: ```/\d[.]\d[.]\d/```

Option hideSha was introduced in #36 

I have several suggestions:

* Make the matching more robust. I don't even see a reason to use a regex. Splitting on + (the sign used in SemVer to separate build metadata from the rest of the version) should be enough.
* If for some reason something doesn't match return an empty string but don't break the whole app

As long as the hideSha Option is not used everything should continue to work as before so this is not critical. But especially the first issue (not accepting version 1.10.0) will probably lead to some head-scratching when using the Option.

**Comment by taras** [comment]
@omarkohl sounds like great ideas. I'm open to a PR to add this.

**Comment by Techn1x** [comment]
Also solved by https://github.com/ember-cli/ember-cli-app-version/pull/60
