### ISSUE TITLE
Allow fetching of SHA from Env var

### ISSUE THREAD

**Issue by mirague** [ember-cli/ember-cli-app-version#41]
When building the app on Heroku for example, there is no `.git` folder during the build process. This results in version numbers like `1.0.2+` because the SHA commit hash is missing.

Heroku -does- expose the commit hash in a [`SOURCE_VERSION`](https://devcenter.heroku.com/changelog-items/630) environment variable that we could tap into in this case.

Any thoughts in how this could be achieved? Perhaps being able to pass in a custom resolver during build could be beneficial?

**Comment by taras** [comment]
We could make it possible to specify version via the `config/environment.js`. 

In case of Heroku, it would be something like this,

```js
/* jshint node: true */

module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'dummy',
    environment: environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {

  }

   ENV['ember-cli-app-version'] = {
      version: process.env.SOURCE_VERSION
   };

  return ENV;
};
```

In [`index.js`](https://github.com/EmberSherpa/ember-cli-app-version/blob/master/index.js#L10) we would check if `version` option is set and use it instead of the git version.

Alternatively, we could just use `APP_VERSION` environment variable so you could something like this,

```sh
APP_VERSION=SOURCE_VERSION ember build
```

Do you have a preference?

**Comment by alexlafroscia** [comment]
I think allowing it to be overwritten in `config/environment.js`, falling back to the manual lookup, sounds like a really elegant solution.

**Comment by mirague** [comment]
@taras @alexlafroscia I agree, being able to overwrite it in `config/environment.js` would give sufficient control for this case.

**Comment by taras** [comment]
@mirague would you like to put together a PR? 😊

**Comment by mirague** [comment]
@taras I would love to but I'm afraid I would have no clue where to get started. New to the whole Ember eco-system..

**Comment by taras** [comment]
I can tell you and you can give it a try - if you want.

**Comment by mirague** [comment]
That sounds good to me!

**Comment by taras** [comment]
Ok, here are the steps:

1. Fork this repo, so you'll have something like `github.com/mirague/ember-cli-app-version`
2. Clone that repo locally
3. Run `npm install && bower install` inside of local `ember-cli-app-version` directory
4. Run `npm link`, this will make this project available for linking inside of your app
5. Go into your app and run `npm link ember-cli-app-version`
6. Now you're ready to dev
7. Add to your app's `environment/config.js`
    ```js
     ENV['ember-cli-app-version'] = {
      version: process.env.SOURCE_VERSION
     };
    ```
8. On [line 9 in ember-cli-app-version/index.js](https://github.com/EmberSherpa/ember-cli-app-version/blob/master/index.js#L9) you will have access to configurations that are specified in your app's `config/environment.js`
9. You can `console.log(config)` to see what you get there
10. You should be able to do something like this
    ```js
     if (config.version) {
        return config;
     }
     ```
11. Test it by running `APP_VERSION=123412.123124 ember serve`
12. Commit change and create a PR

Try this and let me know how it goes

**Comment by mirague** [comment]
Giving this a go now!
