### ISSUE TITLE
no SHA when git tag is present

### ISSUE THREAD

**Issue by jamesdixon** [ember-cli/ember-cli-app-version#48]
Hi,

It appears that no SHA is displayed when a git tag is present. Is this intended behavior? I'd love to be able to still display the SHA even if there is a tag given that I typically use `npm version` to update my package.json.

Thanks!

**Comment by PratheepV** [comment]
+1

**Comment by arnebit** [comment]
Is this still an issue? We just had this issue and it seemed to have gone away after updating to the latest version.

`git-repo-version`'s main method up to version 0.4.1 (as used in `ember-cli-app-version`) did return a bit too early sometimes if a tag was present, but [this seems to have been changed ](https://github.com/cibernox/git-repo-version/commit/6c88737b5452e8e9cea19bb35c5b7e9766b2a25a#diff-168726dbe96b3ce427e7fedce31bb0bcL13)for git-repo-version 1.0.0 (used in ember-cli-app-version >3.1.0).
