### ISSUE TITLE
hideSha regex fails on some version numbers

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli-app-version#62]
Example: `0.10.0+0fbd02d5`

This version number caused the regex to not find a match, which made the helper error out and break the consuming app.

**Comment by localpcguy** [comment]
Literally just ran into this same error, the proper regex should be `/\d+[.]\d+[.]\d+/` I believe

**Comment by localpcguy** [comment]
Looks like #60 and #61 both address this, but have more than just a fix for this specific issue. Happy to supply a really simple PR that just addresses this issue if that would be simpler to be accepted than something that has a larger scope.
