### ISSUE TITLE
remove layers of abstraction

### ISSUE THREAD

**Issue by luxferresum** [ember-cli/ember-cli-app-version#64]
Currently we have `ember-cli/ember-cli-app-version` which uses `cibernox/git-repo-version` which uses `rwjblue/git-repo-info`. I think this is too much complexity for this problem.

Also I think more and better configuration would be nice for `ember-cli-app-version`.
Also it seems (#49, #50, cibernox/git-repo-version#9) that we need some configuration.
Ideally I think would be to have some kind of template string the user can provide, to specify which information in which order should be shown. At least we should have a way to display everything provided by `rwjblue/git-repo-info`.

My suggestion is to remove `cibernox/git-repo-version` and directly rely on `rwjblue/git-repo-info`. Then we could allow the user to provide a format function that takes the info from `rwjblue/git-repo-info` and have a sane default. Also we could provide the `prefix`, which calculation is currently the most complex thing `git-repo-version/index.js` does.

something like this looks like a possible solution in my opinion:

    formatFunction: ({prefix, sha, authorDate}) => `${prefix}${sha ? `+${sha}` : ''} ${authorDate}`,

any thoughts?

**Comment by stefanpenner** [comment]
whats the downside?

**Comment by luxferresum** [comment]
what about complexity and boilerplate code?

I've had a chat in slack with @twokul about #49 and we've encountered this confusion. But I also got confused about which repo is which far to often myself.

Also for most changes this means we have to change 2 or maybe even 3 repos. This makes contribution harder.

**Comment by stefanpenner** [comment]
@luxferresum i think you misunderstand, I am agree with you. I am merely asking if you have identified any downsides?

**Comment by luxferresum** [comment]
@stefanpenner yes, sorry, I totally misunderstood!

I only see one downside: We probably will loose maintainers for `cibernox/git-repo-version`, and if any other project then `ember-cli-app-version` uses it, they have to maintain it themselves or drop it as we do.

**Comment by stefanpenner** [comment]
@luxferresum i think thats fine. cc @cibernox thoughts?

**Comment by cibernox** [comment]
sure, if you find it useful let's cut the middleman

**Comment by rwjblue** [comment]
I'm happy to add more maintainers to rwjblue/git-repo-info also. It has at least @hjdivad and myself, but can also add @stefanpenner and @cibernox if they want...
